#!/usr/bin/env bun
/**
 * Local dev launcher. Machine-specific values — the port and the URL vars
 * that embed it — come from the worktree's shared .env (written by setup's
 * per-worktree port allocator, offset +14), not from wrangler.jsonc; this
 * script folds them, plus the secrets from .dev.vars, into a generated
 * .dev.vars.dev and hands wrangler the port. A bare `bun run dev` with no
 * .env still works on the 8787/3000 fallbacks.
 */
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const appDir = join(import.meta.dir, "..");
const repoRoot = join(appDir, "..", "..");

function parseEnvFile(path: string): Record<string, string> {
	if (!existsSync(path)) return {};
	const out: Record<string, string> = {};
	for (const line of readFileSync(path, "utf8").split("\n")) {
		const match = /^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*"?([^"\n]*)"?\s*$/.exec(
			line,
		);
		if (match) out[match[1] as string] = (match[2] as string).trim();
	}
	return out;
}

const rootEnv = parseEnvFile(join(repoRoot, ".env"));
const port = Number(
	process.env.USERCONTENT_DEV_PORT ?? rootEnv.USERCONTENT_DEV_PORT ?? 8787,
);
const webPort = Number(process.env.WEB_PORT ?? rootEnv.WEB_PORT ?? 3000);

// .dev.vars stays the human-owned secrets file; wrangler reads
// .dev.vars.dev INSTEAD of it for --env dev, so the secrets are folded in.
const secrets = parseEnvFile(join(appDir, ".dev.vars"));
const generated = [
	"# Generated by scripts/dev.ts from the worktree's .env — do not edit.",
	...Object.entries(secrets).map(([key, value]) => `${key}=${value}`),
	`USERCONTENT_URL=http://frame.usercontent.localhost:${port}`,
	`MEDIA_URL=http://media.usercontent.localhost:${port}`,
	`APP_URL=http://localhost:${webPort}`,
	"FRAME_ANCESTORS=http://localhost:* file:",
	"",
].join("\n");
writeFileSync(join(appDir, ".dev.vars.dev"), generated);

console.log(`[usercontent] wrangler dev on :${port} (app :${webPort})`);
const result = spawnSync(
	"bunx",
	["wrangler", "dev", "--env", "dev", "--port", String(port)],
	{ stdio: "inherit", cwd: appDir },
);
process.exit(result.status ?? 0);
